version: '2'
services:
    disasterservice-postgresql:
        container_name: disasterservice-postgresql
        image: postgres:9.5.2
        # volumes:
        #     - ~/volumes/jhipster/DisasterService/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=DisasterService
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
